spring:
  profiles:
    default: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 200
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  redis:
    host: ${REDIS_HOST} localhost
    port: ${REDIS_PORT} 6379


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30  # 30분
  refresh-token-expiration-minutes: 10080 # 1주일