spring:
  profiles:
    default: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 200
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}

imp:
  key: ${IMP_KEY}
  secret: ${IMP_SECRET}

