package com.hobbyt.global.error.exception;

import static org.springframework.http.HttpStatus.*;

import org.springframework.http.HttpStatus;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ExceptionCode {
	MEMBER_NOT_FOUND(NOT_FOUND, "MEMBER_NOT_FOUND"),
	MEMBER_EMAIL_DUPLICATED(CONFLICT, "EMAIL_DUPLICATED"),
	MEMBER_NICKNAME_DUPLICATED(CONFLICT, "NICKNAME_DUPLICATED"),

	AUTH_INVALID_PASSWORD(BAD_REQUEST, "INVALID_PASSWORD"),

	SALE_NOT_FOUND(NOT_FOUND, "SALE_NOT_FOUND"),

	PRODUCT_NOT_FOUND(NOT_FOUND, "PRODUCT_NOT_FOUND"),
	PRODUCT_STOCK_NOT_ENOUGH(CONFLICT, "STOCK_NOT_ENOUGH"),

	ORDER_NOT_FOUND(NOT_FOUND, "ORDER_NOT_FOUND"),

	POST_NOT_FOUND(NOT_FOUND, "POST_NOT_FOUND"),

	COMMENT_NOT_FOUND(NOT_FOUND, "COMMENT_NOT_FOUND"),

	ORDER_CANCEL_NOT_PERMITTED(CONFLICT, "ORDER_CANCEL_NOT_PERMITTED"),
	REFUND_NOT_PERMITTED(CONFLICT, "REFUND_NOT_PERMITTED"),

	FILE_NOT_FOUND(NOT_FOUND, "FILE_NOT_FOUND"),
	FILE_UPLOAD_FAILED(INTERNAL_SERVER_ERROR, "FAILED_TO_UPLOAD_FILE"),
	FILE_DOWNLOAD_FAILED(INTERNAL_SERVER_ERROR, "FAILED_TO_DOWNLOAD_FILE"),
	MAIL_SEND_FAILED(INTERNAL_SERVER_ERROR, "FAILED_TO_SEND_MAIL"),
	FILE_EMPTY_UPLOADED(BAD_REQUEST, "EMPTY_FILE_UPLOADED"),
	FILE_NOT_IMAGE_UPLOADED(BAD_REQUEST, "NOT_IMAGE_FILE_UPLOADED"),
	WRONG_PERIOD(BAD_REQUEST, "WRONG_PERIOD"),

	RESOURCE_NOT_FOUND(NOT_FOUND, "NOT_FOUND"),
	UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
	FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN");

	private final HttpStatus status;
	private final String message;
}
